# Basic Usage

`tidystats` is an experimental new module in `pymer4` that aims to bring more R "tidy" functionality to Python and expand the scope of great libraries available. This demo includese

In [1]:
import pymer4.tidystats as ts

## Included datasets

In [2]:
mtcars = ts.load_dataset('mtcars')
mtcars.head()

shape: (5, 12)
┌───────────────────┬──────┬─────┬───────┬───┬─────┬─────┬──────┬──────┐
│ model             ┆ mpg  ┆ cyl ┆ disp  ┆ … ┆ vs  ┆ am  ┆ gear ┆ carb │
│ ---               ┆ ---  ┆ --- ┆ ---   ┆   ┆ --- ┆ --- ┆ ---  ┆ ---  │
│ str               ┆ f64  ┆ i64 ┆ f64   ┆   ┆ i64 ┆ i64 ┆ i64  ┆ i64  │
╞═══════════════════╪══════╪═════╪═══════╪═══╪═════╪═════╪══════╪══════╡
│ Mazda RX4         ┆ 21.0 ┆ 6   ┆ 160.0 ┆ … ┆ 0   ┆ 1   ┆ 4    ┆ 4    │
│ Mazda RX4 Wag     ┆ 21.0 ┆ 6   ┆ 160.0 ┆ … ┆ 0   ┆ 1   ┆ 4    ┆ 4    │
│ Datsun 710        ┆ 22.8 ┆ 4   ┆ 108.0 ┆ … ┆ 1   ┆ 1   ┆ 4    ┆ 1    │
│ Hornet 4 Drive    ┆ 21.4 ┆ 6   ┆ 258.0 ┆ … ┆ 1   ┆ 0   ┆ 3    ┆ 1    │
│ Hornet Sportabout ┆ 18.7 ┆ 8   ┆ 360.0 ┆ … ┆ 0   ┆ 0   ┆ 3    ┆ 2    │
└───────────────────┴──────┴─────┴───────┴───┴─────┴─────┴──────┴──────┘

## Cleaning with janitor

In [3]:
ts.get_dupes(mtcars, 'mpg', 'hp')

shape: (2, 13)
┌──────┬─────┬────────────┬───────────────┬───┬─────┬─────┬──────┬──────┐
│ mpg  ┆ hp  ┆ dupe_count ┆ model         ┆ … ┆ vs  ┆ am  ┆ gear ┆ carb │
│ ---  ┆ --- ┆ ---        ┆ ---           ┆   ┆ --- ┆ --- ┆ ---  ┆ ---  │
│ f64  ┆ i32 ┆ i32        ┆ str           ┆   ┆ i32 ┆ i32 ┆ i32  ┆ i32  │
╞══════╪═════╪════════════╪═══════════════╪═══╪═════╪═════╪══════╪══════╡
│ 21.0 ┆ 110 ┆ 2          ┆ Mazda RX4     ┆ … ┆ 0   ┆ 1   ┆ 4    ┆ 4    │
│ 21.0 ┆ 110 ┆ 2          ┆ Mazda RX4 Wag ┆ … ┆ 0   ┆ 1   ┆ 4    ┆ 4    │
└──────┴─────┴────────────┴───────────────┴───┴─────┴─────┴──────┴──────┘

In [4]:
titanic = ts.load_dataset('titanic_train').drop_nulls()
titanic.glimpse()

Rows: 183
Columns: 12
$ PassengerId <i64> 2, 4, 7, 11, 12, 22, 24, 28, 53, 55
$ Survived    <i64> 1, 1, 0, 1, 1, 1, 1, 0, 1, 0
$ Pclass      <i64> 1, 1, 1, 3, 1, 2, 1, 1, 1, 1
$ Name        <str> 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)', 'Futrelle, Mrs. Jacques Heath (Lily May Peel)', 'McCarthy, Mr. Timothy J', 'Sandstrom, Miss. Marguerite Rut', 'Bonnell, Miss. Elizabeth', 'Beesley, Mr. Lawrence', 'Sloper, Mr. William Thompson', 'Fortune, Mr. Charles Alexander', 'Harper, Mrs. Henry Sleeper (Myna Haxtun)', 'Ostby, Mr. Engelhart Cornelius'
$ Sex         <str> 'female', 'female', 'male', 'female', 'female', 'male', 'male', 'male', 'female', 'male'
$ Age         <f64> 38.0, 35.0, 54.0, 4.0, 58.0, 34.0, 28.0, 19.0, 49.0, 65.0
$ SibSp       <i64> 1, 1, 0, 1, 0, 0, 0, 3, 1, 0
$ Parch       <i64> 0, 0, 0, 1, 0, 0, 0, 2, 0, 1
$ Ticket      <str> 'PC 17599', '113803', '17463', 'PP 9549', '113783', '248698', '113788', '19950', 'PC 17572', '113509'
$ Fare        <f64> 71.2833, 53.1, 51.8625, 16.7, 26.55, 13.0, 35.5, 263.0, 76.7292, 61.9792
$ Cabin       <str> 'C85', 'C123', 'E46', 'G6', 'C103', 'D56', 'A6', 'C23 C25 C27', 'D33', 'B30'
$ Embarked    <str> 'C', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'C', 'C'

In [5]:
titanic = ts.clean_names(titanic)
titanic.glimpse()

Rows: 183
Columns: 12
$ passenger_id <i32> 2, 4, 7, 11, 12, 22, 24, 28, 53, 55
$ survived     <i32> 1, 1, 0, 1, 1, 1, 1, 0, 1, 0
$ pclass       <i32> 1, 1, 1, 3, 1, 2, 1, 1, 1, 1
$ name         <str> 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)', 'Futrelle, Mrs. Jacques Heath (Lily May Peel)', 'McCarthy, Mr. Timothy J', 'Sandstrom, Miss. Marguerite Rut', 'Bonnell, Miss. Elizabeth', 'Beesley, Mr. Lawrence', 'Sloper, Mr. William Thompson', 'Fortune, Mr. Charles Alexander', 'Harper, Mrs. Henry Sleeper (Myna Haxtun)', 'Ostby, Mr. Engelhart Cornelius'
$ sex          <str> 'female', 'female', 'male', 'female', 'female', 'male', 'male', 'male', 'female', 'male'
$ age          <f64> 38.0, 35.0, 54.0, 4.0, 58.0, 34.0, 28.0, 19.0, 49.0, 65.0
$ sib_sp       <i32> 1, 1, 0, 1, 0, 0, 0, 3, 1, 0
$ parch        <i32> 0, 0, 0, 1, 0, 0, 0, 2, 0, 1
$ ticket       <str> 'PC 17599', '113803', '17463', 'PP 9549', '113783', '248698', '113788', '19950', 'PC 17572', '113509'
$ fare         <f64> 71.2833, 53.1, 51.8625, 16.7, 26.55, 13.0, 35.5, 263.0, 76.7292, 61.9792
$ cabin        <str> 'C85', 'C123', 'E46', 'G6', 'C103', 'D56', 'A6', 'C23 C25 C27', 'D33', 'B30'
$ embarked     <str> 'C', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'C', 'C'

## Linear regression with lm

In [6]:
df = ts.load_dataset('sleep')
model = ts.lm('Reaction ~ Days', data=df)

Basic functions that work with models like `resid`

In [7]:
# First 3 residuals
ts.resid(model)[:3]

array([ -1.84510485,  -3.16769081, -21.53907677])

And `coef`

In [8]:
# Coefficients
ts.coef(model)

array([251.40510485,  10.46728596])

## Tidy model manipulation

`tidy`, `glance`, and `augment` from [broom](https://broom.tidymodels.org/)

In [9]:
# Summary table
ts.tidy(model)

shape: (2, 5)
┌─────────────┬────────────┬───────────┬───────────┬────────────┐
│ term        ┆ estimate   ┆ std_error ┆ statistic ┆ p_value    │
│ ---         ┆ ---        ┆ ---       ┆ ---       ┆ ---        │
│ str         ┆ f64        ┆ f64       ┆ f64       ┆ f64        │
╞═════════════╪════════════╪═══════════╪═══════════╪════════════╡
│ (Intercept) ┆ 251.405105 ┆ 6.610154  ┆ 38.033169 ┆ 2.1569e-87 │
│ Days        ┆ 10.467286  ┆ 1.238195  ┆ 8.453663  ┆ 9.8941e-15 │
└─────────────┴────────────┴───────────┴───────────┴────────────┘

In [10]:
# Fit statistics
ts.glance(model)

shape: (1, 12)
┌───────────┬─────────────┬──────────┬───────────┬───┬────────────┬────────────┬────────────┬──────┐
│ r_squared ┆ adj_r_squar ┆ sigma    ┆ statistic ┆ … ┆ BIC        ┆ deviance   ┆ df_residua ┆ nobs │
│ ---       ┆ ed          ┆ ---      ┆ ---       ┆   ┆ ---        ┆ ---        ┆ l          ┆ ---  │
│ f64       ┆ ---         ┆ f64      ┆ f64       ┆   ┆ f64        ┆ f64        ┆ ---        ┆ i32  │
│           ┆ f64         ┆          ┆           ┆   ┆            ┆            ┆ i32        ┆      │
╞═══════════╪═════════════╪══════════╪═══════════╪═══╪════════════╪════════════╪════════════╪══════╡
│ 0.286471  ┆ 0.282463    ┆ 47.71472 ┆ 71.464421 ┆ … ┆ 1915.87192 ┆ 405251.617 ┆ 178        ┆ 180  │
│           ┆             ┆          ┆           ┆   ┆ 7          ┆ 48         ┆            ┆      │
└───────────┴─────────────┴──────────┴───────────┴───┴────────────┴────────────┴────────────┴──────┘

In [11]:
# Augment original data with columns of model output
ts.augment(model).head()

shape: (5, 8)
┌──────────┬──────┬────────────┬────────────┬──────────┬───────────┬──────────┬───────────┐
│ Reaction ┆ Days ┆ fitted     ┆ resid      ┆ hat      ┆ sigma     ┆ cooksd   ┆ std_resid │
│ ---      ┆ ---  ┆ ---        ┆ ---        ┆ ---      ┆ ---       ┆ ---      ┆ ---       │
│ f64      ┆ i32  ┆ f64        ┆ f64        ┆ f64      ┆ f64       ┆ f64      ┆ f64       │
╞══════════╪══════╪════════════╪════════════╪══════════╪═══════════╪══════════╪═══════════╡
│ 249.56   ┆ 0    ┆ 251.405105 ┆ -1.845105  ┆ 0.019192 ┆ 47.849112 ┆ 0.000015 ┆ -0.039046 │
│ 258.7047 ┆ 1    ┆ 261.872391 ┆ -3.167691  ┆ 0.013805 ┆ 47.848717 ┆ 0.000031 ┆ -0.066851 │
│ 250.8006 ┆ 2    ┆ 272.339677 ┆ -21.539077 ┆ 0.009764 ┆ 47.82165  ┆ 0.001015 ┆ -0.453634 │
│ 321.4398 ┆ 3    ┆ 282.806963 ┆ 38.632837  ┆ 0.007071 ┆ 47.760496 ┆ 0.002351 ┆ 0.812541  │
│ 356.8519 ┆ 4    ┆ 293.274249 ┆ 63.577651  ┆ 0.005724 ┆ 47.608706 ┆ 0.00514  ┆ 1.336283  │
└──────────┴──────┴────────────┴────────────┴──────────┴───────────┴──────────┴───────────┘

## GLM and contrasts

String variables are encoded as factors by default:

In [12]:
# sex is a string
model = ts.glm('survived ~ 1 + sex', data=titanic, family='binomial')

# Summary
ts.tidy(model)

shape: (2, 5)
┌─────────────┬───────────┬───────────┬───────────┬────────────┐
│ term        ┆ estimate  ┆ std_error ┆ statistic ┆ p_value    │
│ ---         ┆ ---       ┆ ---       ┆ ---       ┆ ---        │
│ str         ┆ f64       ┆ f64       ┆ f64       ┆ f64        │
╞═════════════╪═══════════╪═══════════╪═══════════╪════════════╡
│ (Intercept) ┆ 2.61496   ┆ 0.422919  ┆ 6.183115  ┆ 6.2849e-10 │
│ sexmale     ┆ -2.890372 ┆ 0.470924  ┆ -6.137657 ┆ 8.3747e-10 │
└─────────────┴───────────┴───────────┴───────────┴────────────┘

We can confirm this using the `contrasts` argument to an `lm()`, `glm()`, `lmer()`, and `glmer()` model. This takes a Python dictionary with keys corresponding to variable names and values provides as a either a string referring to a contrast type in R.

In [13]:
# contr.treatment is the default (dummy-coding)
model = ts.glm('survived ~ 1 + sex', data=titanic, family='binomial', contrasts = {'sex': 'contr.treatment'})

# Summary
ts.tidy(model)

shape: (2, 5)
┌─────────────┬───────────┬───────────┬───────────┬────────────┐
│ term        ┆ estimate  ┆ std_error ┆ statistic ┆ p_value    │
│ ---         ┆ ---       ┆ ---       ┆ ---       ┆ ---        │
│ str         ┆ f64       ┆ f64       ┆ f64       ┆ f64        │
╞═════════════╪═══════════╪═══════════╪═══════════╪════════════╡
│ (Intercept) ┆ 2.61496   ┆ 0.422919  ┆ 6.183115  ┆ 6.2849e-10 │
│ sexmale     ┆ -2.890372 ┆ 0.470924  ┆ -6.137657 ┆ 8.3747e-10 │
└─────────────┴───────────┴───────────┴───────────┴────────────┘

## Categorical coding schemes

In [14]:
poker = ts.load_dataset('poker')
poker.glimpse()

Rows: 300
Columns: 4
$ skill   <str> 'expert', 'expert', 'expert', 'expert', 'expert', 'expert', 'expert', 'expert', 'expert', 'expert'
$ hand    <str> 'bad', 'bad', 'bad', 'bad', 'bad', 'bad', 'bad', 'bad', 'bad', 'bad'
$ limit   <str> 'fixed', 'fixed', 'fixed', 'fixed', 'fixed', 'fixed', 'fixed', 'fixed', 'fixed', 'fixed'
$ balance <f64> 4.0, 5.55, 9.45, 7.19, 5.71, 5.32, 8.52, 4.06, 4.97, 6.18

### Treatment/Dummy coding

In [15]:
# Default dummy contrasts
model = ts.lm('balance ~ hand', data=poker)

# Inspect model design matrix
ts.model_matrix(model)

shape: (3, 3)
┌─────────────┬──────────┬─────────────┐
│ (Intercept) ┆ handgood ┆ handneutral │
│ ---         ┆ ---      ┆ ---         │
│ f64         ┆ f64      ┆ f64         │
╞═════════════╪══════════╪═════════════╡
│ 1.0         ┆ 0.0      ┆ 0.0         │
│ 1.0         ┆ 0.0      ┆ 1.0         │
│ 1.0         ┆ 1.0      ┆ 0.0         │
└─────────────┴──────────┴─────────────┘

### Deviation/Sum coding

In [16]:
# Sum-to-zero
sum_model = ts.lm('balance ~ hand', data=poker, contrasts={'hand': 'contr.sum'})

ts.model_matrix(sum_model)

shape: (3, 3)
┌─────────────┬───────┬───────┐
│ (Intercept) ┆ hand1 ┆ hand2 │
│ ---         ┆ ---   ┆ ---   │
│ f64         ┆ f64   ┆ f64   │
╞═════════════╪═══════╪═══════╡
│ 1.0         ┆ 1.0   ┆ 0.0   │
│ 1.0         ┆ -1.0  ┆ -1.0  │
│ 1.0         ┆ 0.0   ┆ 1.0   │
└─────────────┴───────┴───────┘

### Orthogonal Polynomial coding

In [17]:
# Poly
poly_model = ts.lm('balance ~ hand', data=poker, contrasts={'hand': 'contr.poly'})

ts.model_matrix(poly_model)

shape: (3, 3)
┌─────────────┬─────────────┬───────────┐
│ (Intercept) ┆ hand.L      ┆ hand.Q    │
│ ---         ┆ ---         ┆ ---       │
│ f64         ┆ f64         ┆ f64       │
╞═════════════╪═════════════╪═══════════╡
│ 1.0         ┆ -0.707107   ┆ 0.408248  │
│ 1.0         ┆ 0.707107    ┆ 0.408248  │
│ 1.0         ┆ -9.0738e-17 ┆ -0.816497 │
└─────────────┴─────────────┴───────────┘

## Emmeans and Type-3 ANOVA

We can use the `joint_tests()` function from `emmeans()` to automatically perform the appropriate ANOVA style F-tests

In [18]:
model = ts.lm('balance ~ hand * skill', data=poker)

# Handles encoding and type III calculation
ts.joint_tests(model)

shape: (3, 5)
┌────────────┬─────┬───────┬─────────┬────────────┐
│ model term ┆ df1 ┆ df2   ┆ F.ratio ┆ p.value    │
│ ---        ┆ --- ┆ ---   ┆ ---     ┆ ---        │
│ str        ┆ f64 ┆ f64   ┆ f64     ┆ f64        │
╞════════════╪═════╪═══════╪═════════╪════════════╡
│ hand       ┆ 2.0 ┆ 294.0 ┆ 79.169  ┆ 3.1184e-28 │
│ skill      ┆ 1.0 ┆ 294.0 ┆ 2.434   ┆ 0.119778   │
│ hand:skill ┆ 2.0 ┆ 294.0 ┆ 7.083   ┆ 0.00099    │
└────────────┴─────┴───────┴─────────┴────────────┘

## Emmeans marginal comparisons

We can also use `emmeans` to calculate the marginal means, aka "cell-means" from our ANOVA

In [19]:
# Marginal means
ts.emmeans(model, specs='hand', by='skill')

shape: (6, 7)
┌─────────┬─────────┬─────────┬──────────┬───────┬───────────┬───────────┐
│ hand    ┆ skill   ┆ emmean  ┆ SE       ┆ df    ┆ lower.CL  ┆ upper.CL  │
│ ---     ┆ ---     ┆ ---     ┆ ---      ┆ ---   ┆ ---       ┆ ---       │
│ cat     ┆ cat     ┆ f64     ┆ f64      ┆ f64   ┆ f64       ┆ f64       │
╞═════════╪═════════╪═════════╪══════════╪═══════╪═══════════╪═══════════╡
│ bad     ┆ average ┆ 4.5866  ┆ 0.568579 ┆ 294.0 ┆ 3.467599  ┆ 5.705601  │
│ good    ┆ average ┆ 13.7976 ┆ 0.568579 ┆ 294.0 ┆ 12.678599 ┆ 14.916601 │
│ neutral ┆ average ┆ 9.8438  ┆ 0.568579 ┆ 294.0 ┆ 8.724799  ┆ 10.962801 │
│ bad     ┆ expert  ┆ 7.2964  ┆ 0.568579 ┆ 294.0 ┆ 6.177399  ┆ 8.415401  │
│ good    ┆ expert  ┆ 12.2552 ┆ 0.568579 ┆ 294.0 ┆ 11.136199 ┆ 13.374201 │
│ neutral ┆ expert  ┆ 10.8494 ┆ 0.568579 ┆ 294.0 ┆ 9.730399  ┆ 11.968401 │
└─────────┴─────────┴─────────┴──────────┴───────┴───────────┴───────────┘

`tidystats` exposes `emmeans::contrast` as the `contrasts` keyword argument for simplicity. Internally it combines the `emmeans()` and the `contrast()` functions as recommended

In [20]:
# Pairwise comparisons
ts.emmeans(model, specs='hand', by='skill', contrasts='pairwise')

shape: (6, 7)
┌────────────────┬─────────┬──────────┬──────────┬───────┬────────────┬────────────┐
│ contrast       ┆ skill   ┆ estimate ┆ SE       ┆ df    ┆ t.ratio    ┆ p.value    │
│ ---            ┆ ---     ┆ ---      ┆ ---      ┆ ---   ┆ ---        ┆ ---        │
│ cat            ┆ cat     ┆ f64      ┆ f64      ┆ f64   ┆ f64        ┆ f64        │
╞════════════════╪═════════╪══════════╪══════════╪═══════╪════════════╪════════════╡
│ bad - good     ┆ average ┆ -9.211   ┆ 0.804093 ┆ 294.0 ┆ -11.455148 ┆ 7.0255e-13 │
│ bad - neutral  ┆ average ┆ -5.2572  ┆ 0.804093 ┆ 294.0 ┆ -6.538053  ┆ 8.2593e-10 │
│ good - neutral ┆ average ┆ 3.9538   ┆ 0.804093 ┆ 294.0 ┆ 4.917095   ┆ 0.000004   │
│ bad - good     ┆ expert  ┆ -4.9588  ┆ 0.804093 ┆ 294.0 ┆ -6.166951  ┆ 6.8840e-9  │
│ bad - neutral  ┆ expert  ┆ -3.553   ┆ 0.804093 ┆ 294.0 ┆ -4.418645  ┆ 0.000042   │
│ good - neutral ┆ expert  ┆ 1.4058   ┆ 0.804093 ┆ 294.0 ┆ 1.748306   ┆ 0.189135   │
└────────────────┴─────────┴──────────┴──────────┴───────┴────────────┴────────────┘

Which makes it very intuitive to specify custom contrasts and correction factors:

In [21]:
# Custom contrasts
# Across levels of hand, marginalizing over skill
ts.emmeans(model, specs='hand', 
contrasts={
    'bad_neutral_good': [-1, 1, 0],
    '2bad_others': [1, -.5, -.5]
    }, 
adjust='bonferroni')

R[write to console]: NOTE: Results may be misleading due to involvement in interactions

shape: (2, 6)
┌──────────────────┬──────────┬──────────┬───────┬────────────┬────────────┐
│ contrast         ┆ estimate ┆ SE       ┆ df    ┆ t.ratio    ┆ p.value    │
│ ---              ┆ ---      ┆ ---      ┆ ---   ┆ ---        ┆ ---        │
│ str              ┆ f64      ┆ f64      ┆ f64   ┆ f64        ┆ f64        │
╞══════════════════╪══════════╪══════════╪═══════╪════════════╪════════════╡
│ bad_neutral_good ┆ 7.0849   ┆ 0.568579 ┆ 294.0 ┆ 12.460706  ┆ 6.6673e-29 │
│ 2bad_others      ┆ -5.745   ┆ 0.492404 ┆ 294.0 ┆ -11.667245 ┆ 4.1957e-26 │
└──────────────────┴──────────┴──────────┴───────┴────────────┴────────────┘